# Generated by Django 5.0.4 on 2024-05-12 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlibros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstudiante', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField()),
                ('fecharegistro', models.DateField()),
                ('fechaultimoprestamo', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='EstadoLibro',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='FechaLanzamiento',
        ),
        migrations.AddField(
            model_name='libros',
            name='issbn',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='libros',
            name='nejemplar',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='libros',
            name='nombreEditorial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='FechaDevolucion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
